# Generated by Django 5.0.4 on 2024-05-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atiende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Atiende',
                'verbose_name_plural': 'Atienden',
                'db_table': 'Atiende',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidad',
                'db_table': 'Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('clave', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('dias_atencion', models.DateField()),
                ('horarios_atencion', models.TimeField()),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'Medico',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_paciente', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('clave', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'Paciente',
            },
        ),
        migrations.AddConstraint(
            model_name='especialidad',
            constraint=models.UniqueConstraint(fields=('nombre',), name='Uk_Especialidad_nombre'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.especialidad'),
        ),
        migrations.AddField(
            model_name='atiende',
            name='medico_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.medico'),
        ),
        migrations.AddConstraint(
            model_name='paciente',
            constraint=models.UniqueConstraint(fields=('dni_paciente',), name='Uk_Paciente_dni'),
        ),
        migrations.AddField(
            model_name='atiende',
            name='paciente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.paciente'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('matricula',), name='Uk_Medico_matricula'),
        ),
        migrations.AddConstraint(
            model_name='atiende',
            constraint=models.UniqueConstraint(fields=('medico_id', 'paciente_id'), name='Uk_Medico_Paciente'),
        ),
    ]
