# Generated by Django 5.0.4 on 2024-05-05 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSalus', '0002_medico_medicouser_paciente_pacienteuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.TimeField()),
                ('pagado', models.BooleanField()),
                ('estado', models.CharField(blank=True, choices=[('Concluido', 'Concluido'), ('Rechazado', 'Rechazado'), ('Pendiento', 'Pendiento')], default='Rechazado', max_length=45)),
                ('id_especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.especialidad')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.paciente')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'Turno',
            },
        ),
        migrations.CreateModel(
            name='RegistroDeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('sintomas', models.CharField(max_length=254)),
                ('diagnostico', models.CharField(max_length=254)),
                ('tratamiento', models.CharField(max_length=254)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.turno')),
            ],
            options={
                'verbose_name': 'RegistroDeConsulta',
                'verbose_name_plural': 'RegistrosDeConsultas',
                'db_table': 'RegistroDeConsulta',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(blank=True, choices=[('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Rechazado', max_length=45)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appSalus.turno')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
            },
        ),
    ]
