# Generated by Django 5.0.6 on 2024-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='paciente/perfil/no-img.png', upload_to='paciente/perfil', verbose_name='foto perfil paciente'),
        ),
    ]
