# Generated by Django 5.0.6 on 2024-07-12 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='horariodeatencion',
            options={'verbose_name': 'HorarioDeAtencion', 'verbose_name_plural': 'HorariosDeAtenciones'},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_obra_social',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.obrasocial'),
        ),
    ]
