# Generated by Django 5.0.6 on 2024-06-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='obra_social',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='TurnosDisponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.medico')),
            ],
            options={
                'verbose_name': 'TurnosDisponible',
                'verbose_name_plural': 'TurnosDisponibles',
                'db_table': 'TurnosDisponibles',
            },
        ),
        migrations.AddConstraint(
            model_name='turnosdisponibles',
            constraint=models.UniqueConstraint(fields=('dia', 'hora', 'medico'), name='Uk_TurnosDisponibles'),
        ),
    ]
