# Generated by Django 5.0.6 on 2024-06-14 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='foto',
        ),
    ]
