# Generated by Django 5.0.6 on 2024-05-28 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_paciente_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto',
        ),
    ]
