# Generated by Django 5.0.4 on 2024-05-12 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_especialidad_horariodeatencion_medico_pago_turno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('sintomas', models.CharField(max_length=300)),
                ('diagnostico', models.CharField(max_length=300)),
                ('tratamiento', models.CharField(max_length=300)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.turno')),
            ],
            options={
                'verbose_name': 'RegistroDeConsulta',
                'verbose_name_plural': 'RegistrosDeConsultas',
                'db_table': 'RegistroDeConsulta',
            },
        ),
    ]
