# Generated by Django 5.0.4 on 2024-05-09 23:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_especialidad_turno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioDeAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_de_la_semana', models.CharField(max_length=150)),
                ('hora_entrada', models.TimeField(default=datetime.time(8, 0))),
                ('hora_salida', models.TimeField(default=datetime.time(16, 0))),
            ],
            options={
                'verbose_name': 'HorarioDeAtencion',
                'verbose_name_plural': 'HorarioDeAtencion',
                'db_table': 'HorarioDeAtencion',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=11, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('clave', models.CharField(max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'verbose_name': 'Medico',
                'verbose_name_plural': 'Medicos',
                'db_table': 'Medico',
            },
        ),
        migrations.RemoveField(
            model_name='turno',
            name='id_especialidad',
        ),
        migrations.AddField(
            model_name='especialidad',
            name='duracion',
            field=models.TimeField(default=datetime.time(1, 0)),
        ),
        migrations.AlterField(
            model_name='turno',
            name='id_paciente',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.paciente'),
        ),
        migrations.AddConstraint(
            model_name='horariodeatencion',
            constraint=models.UniqueConstraint(fields=('dia_de_la_semana', 'hora_entrada', 'hora_salida'), name='Uk_HorarioDeAtencion'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.especialidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='id_horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.horariodeatencion'),
        ),
        migrations.AddField(
            model_name='medico',
            name='medicoUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='turno',
            name='id_medico',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.medico'),
        ),
        migrations.AddConstraint(
            model_name='medico',
            constraint=models.UniqueConstraint(fields=('matricula',), name='Uk_Medico'),
        ),
    ]
