# Generated by Django 5.0.6 on 2024-06-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_remove_especialidad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='foto',
            field=models.ImageField(default='especialidades/no-especialidad.jpg', upload_to='especialidades', verbose_name='foto especialidad'),
        ),
    ]
