# Generated by Django 5.0.6 on 2024-07-12 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='id_obra_social',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.obrasocial'),
        ),
    ]
