# Generated by Django 5.0.4 on 2024-05-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0002_especialidad_horariodeatencion_medico_pago_turno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='paciente/perfil/no-img.png', upload_to='paciente/perfil'),
        ),
    ]
