# Generated by Django 5.0.6 on 2024-06-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0003_remove_turno_fecha_remove_turno_horario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horariodeatencion',
            options={'verbose_name': 'HorarioDeAtencion', 'verbose_name_plural': 'HorariosDeAtencion'},
        ),
        migrations.RemoveConstraint(
            model_name='horariodeatencion',
            name='Uk_HorarioDeAtencion',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id_horario',
        ),
        migrations.AddField(
            model_name='horariodeatencion',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SalusEcommerce.medico'),
        ),
        migrations.AddConstraint(
            model_name='horariodeatencion',
            constraint=models.UniqueConstraint(fields=('medico', 'dia_de_la_semana', 'hora_entrada', 'hora_salida'), name='Uk_HorarioDeAtencion'),
        ),
    ]
