# Generated by Django 5.0.6 on 2024-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0003_alter_paciente_id_obra_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='foto',
            field=models.ImageField(blank=True, default='obras-sociales/no-obra-social.png', upload_to='obras-sociales', verbose_name='foto obra social'),
        ),
    ]
