# Generated by Django 5.0.6 on 2024-06-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0003_remove_paciente_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='pacienteUser',
            new_name='id_pacienteUser',
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='paciente/perfil/no-img.png', upload_to='paciente/perfil', verbose_name='foto perfil paciente'),
        ),
    ]
