# Generated by Django 5.0.4 on 2024-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0003_paciente_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(default='paciente/perfil/no-img.png', upload_to='paciente/perfil', verbose_name='foto perfil paciente'),
        ),
    ]
