# Generated by Django 5.0.6 on 2024-07-24 06:30

import SalusEcommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0004_obrasocial_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='hora',
            field=models.TimeField(blank=True, default=SalusEcommerce.models.current_time),
        ),
    ]
