# Generated by Django 5.0.6 on 2024-06-02 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0004_rename_pacienteuser_paciente_id_pacienteuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='id_pacienteUser',
            new_name='pacienteUser',
        ),
    ]
