# Generated by Django 5.0.6 on 2024-07-24 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0005_alter_pago_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='hora',
            field=models.TimeField(blank=True, default=datetime.time(6, 39, 59, 615619)),
        ),
    ]
