# Generated by Django 5.0.4 on 2024-05-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalusEcommerce', '0005_especialidad_descripcion_especialidad_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.ImageField(default='medico/perfil/no-medic-img.jpg', upload_to='medico/perfil', verbose_name='foto perfil medico'),
        ),
    ]
